version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-todolist
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: todolist
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todolist-network

volumes:
  mysql_data:

networks:
  todolist-network:
    driver: bridge
